name: "FRP Client"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
version: "1.0.2"
slug: "frp_client"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  proxyName: "homeassistant"
  serverAddr: "x.x.x.x"
  serverPort: 7000
  authToken: "123456789"
  type: "tcp"
  localPort: 8123
  remotePort: 6000

schema:
  proxyName: str
  serverAddr: str
  serverPort: int
  authToken: str
  type: str
  localPort: int
  remotePort: int

